# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en-US
tone_instructions: 'You are an expert code reviewer in TypeScript, JavaScript, and NodeJS. You work in an enterprise software developer team, providing concise and clear code review advice. You only elaborate or provide detailed explanations when requested.'
early_access: true
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: 'Generate concise titles that describe the main change'
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: true
  poem: true
  labeling_instructions: []
  path_filters:
    - "!packages/ims-client/index.ts"
  path_instructions:
    - path: "**/*.{ts,tsx}"
      instructions: |
        Follow .cursor/rules/typescript-patterns.mdc for general TypeScript conventions.
        Prefer code and comments in English for team readability and focus on architectural patterns.

    - path: "apps/web/**/*.{ts,tsx}"
      instructions: |
        Frontend Next.js application - verify component composition, state management,
        error boundaries, performance optimizations, and accessibility best practices.

    - path: "apps/server/**/*.ts"
      instructions: |
        Encore backend application. Follow cursor rules:
        .cursor/rules/controller-patterns.mdc
        .cursor/rules/error-handling.mdc
        .cursor/rules/feature-pattern.mdc
        .cursor/rules/secrets-patterns.mdc

    - path: "apps/server/**/*controller.ts"
      instructions: |
        Follow .cursor/rules/controller-patterns.mdc

    - path: "apps/server/**/*repository.ts"
      instructions: |
        Follow .cursor/rules/database-patterns.mdc

    - path: "apps/server/**/*.types.ts"
      instructions: |
        Follow .cursor/rules/types-patterns.mdc

    - path: "apps/server/**/*schema.ts"
      instructions: |
        Follow .cursor/rules/database-patterns.mdc
        Verify that appropriate database indexes are defined for:
        - Foreign keys
        - Queried columns
        Ensure indexes improve query performance without over-indexing.

    - path: "apps/server/**/*use-cases.ts"
      instructions: |
        Follow .cursor/rules/use-cases-patterns.mdc

    - path: "apps/server/**/*.test.ts"
      instructions: |
        Follow .cursor/rules/testing-patterns.mdc

    - path: "packages/**/*.ts"
      instructions: |
        Follow .cursor/rules/typescript-patterns.mdc

    - path: "apps/docs/**"
      instructions: |
        Ensure documentation reflects current behavior and patterns from .cursor/rules/

  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: true
    base_branches:
      - "enhancement/*"
      - "feature/*"
      - "fix/*"
      - "ft/*"
      - "refactor/*"
      - "release/*"
      - "web/*"

  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false

  tools:
    ast-grep:       { essential_rules: true, rule_dirs: [], util_dirs: [], packages: [] }
    shellcheck:     { enabled: false }
    ruff:           { enabled: false }
    markdownlint:   { enabled: true }
    github-checks:  { enabled: true, timeout_ms: 90000 }
    languagetool:   { enabled: true, enabled_only: false, level: default }
    biome:          { enabled: true }
    hadolint:       { enabled: false }
    swiftlint:      { enabled: false }
    phpstan:        { enabled: false }
    golangci-lint:  { enabled: false }
    yamllint:       { enabled: true }
    gitleaks:       { enabled: true }
    checkov:        { enabled: false }
    detekt:         { enabled: false }
    eslint:         { enabled: true }
    rubocop:        { enabled: false }
    buf:            { enabled: false }
    regal:          { enabled: false }
    actionlint:     { enabled: true }
    pmd:            { enabled: false }
    cppcheck:       { enabled: false }
    semgrep:        { enabled: true }
    circleci:       { enabled: false }
    sqlfluff:       { enabled: false }
    prismaLint:     { enabled: false }
    oxc:            { enabled: true }
    shopifyThemeCheck: { enabled: false }

chat:
  auto_reply: true
  integrations:
    jira:   { usage: disabled }
    linear: { usage: disabled }

knowledge_base:
  opt_out: false
  web_search:       { enabled: true }
  learnings:        { scope: local }
  issues:           { scope: local }
  jira:             { usage: disabled, project_keys: [] }
  linear:           { usage: disabled, team_keys: [] }
  pull_requests:    { scope: local }

code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []